

import type { Product } from './types';

const MOCK_PRODUCTS_RAW = [
  // Keyrings (15)
  { id: '1',  category_ko: '아크릴', subCategory_ko: 'keyring',  name_ko: '[아크릴키링 주문제작] 투명아크릴', price: 1200, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '2',  category_ko: '아크릴', subCategory_ko: 'keyring',  name_ko: '[아크릴키링 주문제작] 하프미러 아크릴', price: 1700, reviews: 0,  likes: 0,  image: 'https://placehold.co/300x300.png' },
  { id: '3',  category_ko: '아크릴', subCategory_ko: 'keyring',  name_ko: '[아크릴키링 주문제작] 글리터 아크릴', price: 1200, reviews: 0,  likes: 0,  image: 'https://placehold.co/300x300.png' },
  { id: '4',  category_ko: '아크릴', subCategory_ko: 'keyring',  name_ko: '[아크릴키링 주문제작] 유색/투명컬러/아스텔 아크릴', price: 1200, reviews: 0,  likes: 0,  image: 'https://placehold.co/300x300.png' },
  { id: '5',  category_ko: '아크릴', subCategory_ko: 'keyring',  name_ko: '[아크릴키링 주문제작] 자개 아크릴', price: 1200, reviews: 0,   likes: 0,  image: 'https://placehold.co/300x300.png' },
  { id: '6',  category_ko: '아크릴', subCategory_ko: 'keyring',  name_ko: '[아크릴키링 주문제작] 투명아크릴2', price: 1300, reviews: 0,   likes: 0,  image: 'https://placehold.co/300x300.png' },
  { id: '7',  category_ko: '아크릴', subCategory_ko: 'keyring',  name_ko: '[아크릴키링 주문제작] 하프미러 아크릴2', price: 1800, reviews: 0,   likes: 0,  image: 'https://placehold.co/300x300.png' },
  { id: '8',  category_ko: '아크릴', subCategory_ko: 'keyring',  name_ko: '[아크릴키링 주문제작] 글리터 아크릴2', price: 1250, reviews: 0,   likes: 0,  image: 'https://placehold.co/300x300.png' },
  { id: '9',  category_ko: '아크릴', subCategory_ko: 'keyring',  name_ko: '[아크릴키링 주문제작] 유색/투명컬러/아스텔 아크릴2', price: 1350, reviews: 0,   likes: 0,  image: 'https://placehold.co/300x300.png' },
  { id: '10', category_ko: '아크릴', subCategory_ko: 'keyring',  name_ko: '[아크릴키링 주문제작] 자개 아크릴2', price: 1400, reviews: 0,   likes: 0,  image: 'https://placehold.co/300x300.png' },
  { id: '11', category_ko: '아크릴', subCategory_ko: 'keyring',  name_ko: '[아크릴키링 주문제작] 투명아크릴3', price: 1500, reviews: 0,  likes: 0,  image: 'https://placehold.co/300x300.png' },
  { id: '12', category_ko: '아크릴', subCategory_ko: 'keyring',  name_ko: '[아크릴키링 주문제작] 하프미러 아크릴3', price: 1600, reviews: 0,  likes: 0,  image: 'https://placehold.co/300x300.png' },
  { id: '13', category_ko: '아크릴', subCategory_ko: 'keyring',  name_ko: '[아크릴키링 주문제작] 글리터 아크릴3', price: 1700, reviews: 0,  likes: 0,  image: 'https://placehold.co/300x300.png' },
  { id: '14', category_ko: '아크릴', subCategory_ko: 'keyring',  name_ko: '[아크릴키링 주문제작] 유색/투명컬러/아스텔 아크릴3', price: 1750, reviews: 0,  likes: 0,  image: 'https://placehold.co/300x300.png' },
  { id: '15', category_ko: '아크릴', subCategory_ko: 'keyring',  name_ko: '[아크릴키링 주문제작] 자개 아크릴3', price: 1800, reviews: 0,  likes: 0,  image: 'https://placehold.co/300x300.png' },
  { id: '21', category_ko: '아크릴', subCategory_ko: 'korotto',  name_ko: '자립형 두꺼운 아크릴 스탠드 코롯토 (8T/9T)',          price: 1700, reviews: 0,   likes: 0,   image: 'https://placehold.co/300x300.png' },
  { id: '22', category_ko: '아크릴', subCategory_ko: 'korotto',  name_ko: '뒤도바 코롯토 자립형 두꺼운 아크릴 스탠드 (10T)',      price: 2300, reviews: 0,   likes: 0,   image: 'https://placehold.co/300x300.png' },
  { id: '23', category_ko: '아크릴', subCategory_ko: 'korotto',  name_ko: '입체형 코롯토 자립형 두꺼운 아크릴 스탠드 (10T)',      price: 2300, reviews: 0,   likes: 0,   image: 'https://placehold.co/300x300.png' },
  { id: '24', category_ko: '아크릴', subCategory_ko: 'korotto',  name_ko: '렌티큘러 코롯토 두꺼운 아크릴스탠드',                   price: 2600, reviews: 0,   likes: 0,   image: 'https://placehold.co/300x300.png' },
  { id: '31', category_ko: '아크릴', subCategory_ko: 'smarttok', name_ko: '렌티큘러 아크릴 스마트톡 그립 톡홀더 핸드폰톡 맥세이프', price: 2300, reviews: 0,  likes: 0,  image: 'https://placehold.co/300x300.png' },
  { id: '32', category_ko: '아크릴', subCategory_ko: 'smarttok', name_ko: '회전 스핀 돌려돌려 아크릴 스마트톡 맥세이프',           price: 1900, reviews: 0,  likes: 0,  image: 'https://placehold.co/300x300.png' },
  { id: '33', category_ko: '아크릴', subCategory_ko: 'smarttok', name_ko: '[스마트톡] 야광 촉광 아크릴 그립 톡홀더 맥세이프',       price: 1700, reviews: 0,  likes: 0,  image: 'https://placehold.co/300x300.png' },
  { id: '34', category_ko: '아크릴', subCategory_ko: 'smarttok', name_ko: '[스마트톡] 뮤트컬러 파스텔 무광아크릴 스마트톡 제작',   price: 1600, reviews: 0,  likes: 0,  image: 'https://placehold.co/300x300.png' },
  { id: '35', category_ko: '아크릴', subCategory_ko: 'smarttok', name_ko: '더두꺼운 스마트톡 투명 아크릴 5T 주문제작 맥세이프',    price: 2200, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '36', category_ko: '아크릴', subCategory_ko: 'smarttok', name_ko: '더두꺼운 하프미러 스마트톡 핸드폰톡 5T 주문제작',        price: 2700, reviews: 0, likes: 0,  image: 'https://placehold.co/300x300.png' },
  { id: '37', category_ko: '아크릴', subCategory_ko: 'smarttok', name_ko: '홀로그램 스마트톡 핸드폰톡 주문제작',                    price: 2200, reviews: 0,  likes: 0,  image: 'https://placehold.co/300x300.png' },
  { id: '38', category_ko: '아크릴', subCategory_ko: 'smarttok', name_ko: '겨울 스마트톡 핸드폰톡 아크릴 주문제작',                 price: 2200, reviews: 0, likes: 0,  image: 'https://placehold.co/300x300.png' },
  { id: '39', category_ko: '아크릴', subCategory_ko: 'smarttok', name_ko: '스마트톡 핸드폰톡 아크릴 주문제작',                       price: 1900, reviews: 0, likes: 0,  image: 'https://placehold.co/300x300.png' },
  { id: '41', category_ko: '아크릴', subCategory_ko: 'stand', name_ko: '자율형스탠드', price: 1300, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '42', category_ko: '아크릴', subCategory_ko: 'stand', name_ko: '조립형 아크릴 스탠드', price: 4000, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '43', category_ko: '아크릴', subCategory_ko: 'stand', name_ko: '돌려돌려 스핀 아크릴 스탠드', price: 1600, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '44', category_ko: '아크릴', subCategory_ko: 'stand', name_ko: '렌티큘러 아크릴 스탠드', price: 1900, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '45', category_ko: '아크릴', subCategory_ko: 'stand', name_ko: '더큰스탠드', price: 5700, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '46', category_ko: '아크릴', subCategory_ko: 'stand', name_ko: '홀로그램 깨진유리 격자무늬', price: 1900, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '47', category_ko: '아크릴', subCategory_ko: 'stand', name_ko: '아크릴 디오라마 3면 스탠드', price: 4200, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '48', category_ko: '아크릴', subCategory_ko: 'stand', name_ko: '회전 캐릭터 스탠드', price: 8200, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '49', category_ko: '아크릴', subCategory_ko: 'stand', name_ko: '아크릴 안경 스탠드 거치대', price: 14600, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '50', category_ko: '아크릴', subCategory_ko: 'stand', name_ko: '아크릴토퍼/포토프롭', price: 2000, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '51', category_ko: '아크릴', subCategory_ko: 'holder', name_ko: '포카홀더 부착형', price: 3000, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '52', category_ko: '아크릴', subCategory_ko: 'holder', name_ko: '포카홀더 자유형', price: 4300, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '53', category_ko: '아크릴', subCategory_ko: 'holder', name_ko: '회전 포카홀더', price: 8000, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '54', category_ko: '아크릴', subCategory_ko: 'holder', name_ko: '포카홀더 키링', price: 2800, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '55', category_ko: '아크릴', subCategory_ko: 'holder', name_ko: '홀더 부착형 증사홀더', price: 2000, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '56', category_ko: '아크릴', subCategory_ko: 'holder', name_ko: '포토액자 하프미러 아크릴', price: 2300, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '57', category_ko: '아크릴', subCategory_ko: 'holder', name_ko: '포카홀더 고정형 템플릿', price: 3000, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '58', category_ko: '아크릴', subCategory_ko: 'holder', name_ko: '포토액자 투명아크릴', price: 1500, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '61', category_ko: '아크릴', subCategory_ko: 'shaker', name_ko: 'DIY 오픈 스냅 리벳 키링', price: 2900, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '62', category_ko: '아크릴', subCategory_ko: 'shaker', name_ko: '아크릴 쉐이커 완제품', price: 2900, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '63', category_ko: '아크릴', subCategory_ko: 'shaker', name_ko: '미니아크릴 쉐이커 파츠', price: 350, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '71', category_ko: '아크릴', subCategory_ko: 'carabiner', name_ko: '아크릴 카라비너 투명 5T', price: 2800, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '72', category_ko: '아크릴', subCategory_ko: 'carabiner', name_ko: '아크릴 카라비너 파스텔 4T', price: 1500, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '81', category_ko: '아크릴', subCategory_ko: 'mirror', name_ko: '겨울 손거울', price: 2700, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '82', category_ko: '아크릴', subCategory_ko: 'mirror', name_ko: '겨울 아크릴 (은경/미러)', price: 1700, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '91', category_ko: '아크릴', subCategory_ko: 'magnet', name_ko: '투명 아크릴자석', price: 1700, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '92', category_ko: '아크릴', subCategory_ko: 'magnet', name_ko: '아크릴자석 주문제작', price: 1500, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '93', category_ko: '아크릴', subCategory_ko: 'magnet', name_ko: '아크릴자석(돌출형)', price: 1500, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '94', category_ko: '아크릴', subCategory_ko: 'magnet', name_ko: '아크릴 슈즈참', price: 1300, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '95', category_ko: '아크릴', subCategory_ko: 'magnet', name_ko: '아크릴 코스터 아스텔', price: 2700, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '96', category_ko: '아크릴', subCategory_ko: 'magnet', name_ko: '투명 코스터 아크릴', price: 2700, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '97', category_ko: '아크릴', subCategory_ko: 'magnet', name_ko: '뱃지 배지 명찰', price: 1300, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '101', category_ko: '아크릴', subCategory_ko: 'stationery', name_ko: '아크릴 볼펜', price: 1700, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '102', category_ko: '아크릴', subCategory_ko: 'stationery', name_ko: '유색 아크릴 볼펜', price: 1500, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '103', category_ko: '아크릴', subCategory_ko: 'stationery', name_ko: '투명 아크릴 책갈피', price: 1900, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '104', category_ko: '아크릴', subCategory_ko: 'stationery', name_ko: '아크릴집게 3T', price: 1700, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '105', category_ko: '아크릴', subCategory_ko: 'stationery', name_ko: '자석형 아크릴집게', price: 2400, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '106', category_ko: '아크릴', subCategory_ko: 'stationery', name_ko: '아크릴집게 와이드', price: 2200, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '107', category_ko: '아크릴', subCategory_ko: 'stationery', name_ko: '양쪽/한쪽 아크릴집게', price: 1700, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '108', category_ko: '아크릴', subCategory_ko: 'stationery', name_ko: '아크릴 자(잣대)', price: 1700, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '109', category_ko: '아크릴', subCategory_ko: 'stationery', name_ko: '북스탠드 아크릴 책거치대', price: 7600, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '111', category_ko: '아크릴', subCategory_ko: 'cutting', name_ko: '아크릴 재단 (단순형)', price: 250, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id: '112', category_ko: '아크릴', subCategory_ko: 'cutting', name_ko: '아크릴 재단 (복잡형)', price: 400, reviews: 0, likes: 0, image: 'https://placehold.co/300x300.png' },
  { id:'w1', category_ko:'우드', subCategory_ko:'keyring', name_ko:'우드키링 키링만들기 열쇠고리 주문제작', price:1200, reviews:0, likes:0, image:'https://placehold.co/300x300.png' },
  { id:'w2', category_ko:'우드', subCategory_ko:'magnet',  name_ko:'자석 냉장고자석 마그넷 주문제작',       price:1800, reviews:0, likes:0, image:'https://placehold.co/300x300.png' },
  { id:'w3', category_ko:'우드', subCategory_ko:'stand',   name_ko:'우드스탠드 우드굿즈 우드등신대 미니등신대', price:1300, reviews:0,  likes:0,  image:'https://placehold.co/300x300.png' },
  { id:'l1', category_ko:'랜야드', subCategory_ko:'phone', name_ko:'스트랩키링 랜야드 주문제작 열쇠고리 핸드스트랩', price:2100, reviews:0,  likes:0, image:'https://placehold.co/300x300.png' },
  { id:'l2', category_ko:'랜야드', subCategory_ko:'phone', name_ko:'랜야드 미니 스트랩 키링 라벨키링',             price:1100, reviews:0, likes:0, image:'https://placehold.co/300x300.png' },
  { id:'l3', category_ko:'랜야드', subCategory_ko:'neck',  name_ko:'랜야드 넥 스트랩 사원증 행사용 목걸이줄 행사목걸이 소량 주문제작', price:1800, reviews:0, likes:0, image:'https://placehold.co/300x300.png' },
  { id:'l4', category_ko:'랜야드', subCategory_ko:'phone', name_ko:'랜야드 핸드폰 스트랩 커스텀 주문제작 휴대폰스트랩',              price:1500, reviews:0,  likes:0, image:'https://placehold.co/300x300.png' },
];

const categorySlugMapping: Record<string, string> = {
  '아크릴': 'acrylic',
  '우드': 'wood',
  '랜야드': 'lanyard',
  '포장/부자재': 'packaging'
};

export const mockProducts: Product[] = MOCK_PRODUCTS_RAW.map(p => {
    const category_slug = categorySlugMapping[p.category_ko] || p.category_ko.toLowerCase();
    
    return {
        id: p.id,
        categoryId: category_slug,
        subcategory: p.subCategory_ko,
        nameKo: p.name_ko,
        nameEn: p.name_ko, // Fallback to ko
        slug: `${category_slug}-${p.subCategory_ko}-${p.id}`,
        descriptionKo: `설명 ${p.name_ko}`,
        descriptionEn: `Description for ${p.name_ko}`,
        priceKrw: p.price,
        imageUrl: p.image,
        imageUrls: [p.image],
        isFeatured: (p.likes ?? 0) > 100,
        status: "active",
        isPublished: true,
        stockQuantity: 100,
        options: {},
        stats: {
          likeCount: p.likes ?? 0,
          reviewCount: p.reviews ?? 0,
          ratingSum: p.reviews > 0 ? (Math.random() * 2 + 3) * p.reviews : 0, // Mock rating sum
          avgRating: p.reviews > 0 ? (Math.random() * 2 + 3) : 0, // Mock avg rating
        },
        createdAt: new Date(),
        updatedAt: new Date(),
        categoryKo: p.category_ko
    };
});
