name: CI / build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack & pin pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.12.3 --activate
          pnpm -v

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Type Check
        run: pnpm run type-check

      - name: Lint
        run: pnpm run lint

      - name: Build
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: "placeholder"
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "placeholder"
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: "placeholder"
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "placeholder"
          NEXT_PUBLIC_FIREBASE_APP_ID: "placeholder"
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "placeholder"
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: "placeholder"
        run: pnpm run build
